/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    events: Event;
    gallery: Gallery;
    media: Media;
    registrations: Registration;
    'poll-votes': PollVote;
    'quiz-questions': QuizQuestion;
    'quiz-results': QuizResult;
    subscribers: Subscriber;
    raffle: Raffle;
    'raffle-entries': RaffleEntry;
    submissions: Submission;
    'submission-reactions': SubmissionReaction;
    'submission-views': SubmissionView;
    'submission-comments': SubmissionComment;
    'content-reports': ContentReport;
    'photo-battles': PhotoBattle;
    visitors: Visitor;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    registrations: RegistrationsSelect<false> | RegistrationsSelect<true>;
    'poll-votes': PollVotesSelect<false> | PollVotesSelect<true>;
    'quiz-questions': QuizQuestionsSelect<false> | QuizQuestionsSelect<true>;
    'quiz-results': QuizResultsSelect<false> | QuizResultsSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    raffle: RaffleSelect<false> | RaffleSelect<true>;
    'raffle-entries': RaffleEntriesSelect<false> | RaffleEntriesSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    'submission-reactions': SubmissionReactionsSelect<false> | SubmissionReactionsSelect<true>;
    'submission-views': SubmissionViewsSelect<false> | SubmissionViewsSelect<true>;
    'submission-comments': SubmissionCommentsSelect<false> | SubmissionCommentsSelect<true>;
    'content-reports': ContentReportsSelect<false> | ContentReportsSelect<true>;
    'photo-battles': PhotoBattlesSelect<false> | PhotoBattlesSelect<true>;
    visitors: VisitorsSelect<false> | VisitorsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ru' | 'tt') | ('ru' | 'tt')[];
  globals: {
    'festival-map': FestivalMap;
    home: Home;
    'live-stream': LiveStream;
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    'festival-map': FestivalMapSelect<false> | FestivalMapSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    'live-stream': LiveStreamSelect<false> | LiveStreamSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: 'ru' | 'tt';
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Фон шапки страницы. Если не задано — используется тематический декор по смыслу страницы.
   */
  heroImage?: (number | null) | Media;
  publishedAt?: string | null;
  /**
   * Заполняется автоматически из заголовка. Можно переопределить вручную.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  summary?: string | null;
  startDate: string;
  endDate?: string | null;
  location?: string | null;
  /**
   * Например: Главная сцена, Спортивная площадка, Детская поляна. Группирует программу по площадкам.
   */
  venue?: string | null;
  category?: ('concert' | 'sport' | 'food' | 'kids' | 'crafts' | 'ceremony' | 'other') | null;
  heroImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  capacity?: number | null;
  /**
   * Если включено — на сайте показывается форма заявки (этап M2).
   */
  registrationEnabled?: boolean | null;
  publishedAt?: string | null;
  /**
   * Заполняется автоматически из заголовка. Можно переопределить вручную.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  title: string;
  description?: string | null;
  date?: string | null;
  event?: (number | null) | Event;
  coverImage?: (number | null) | Media;
  photos?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  videos?:
    | {
        url: string;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  publishedAt?: string | null;
  /**
   * Заполняется автоматически из заголовка. Можно переопределить вручную.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Заявки посетителей. Содержат персональные данные (152-ФЗ) — доступ только у персонала.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations".
 */
export interface Registration {
  id: number;
  fullName: string;
  phone: string;
  email?: string | null;
  event: number | Event;
  /**
   * Для заявок на майдан-состязания (куреш, скачки, детские игры…).
   */
  competitionType?: ('koresh' | 'skachki' | 'meshki' | 'beg_v_meshkah' | 'kanat' | 'girya' | 'stolb' | 'kids') | null;
  participants: number;
  comment?: string | null;
  /**
   * Обязательно. Посетитель должен подтвердить согласие при отправке заявки.
   */
  consent: boolean;
  status?: ('new' | 'confirmed' | 'cancelled') | null;
  source?: ('website' | 'phone' | 'other') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Голоса анонимного опроса «Любимое состязание». Итоги — на сайте (агрегат).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "poll-votes".
 */
export interface PollVote {
  id: number;
  option: 'koresh' | 'skachki' | 'stolb' | 'meshki' | 'kanat' | 'motokross';
  updatedAt: string;
  createdAt: string;
}
/**
 * Вопросы познавательной игры-угадайки. Факт в «Пояснении» должен иметь проверяемый «Источник». Публикуется только после фактчека (черновик не виден на сайте).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-questions".
 */
export interface QuizQuestion {
  id: number;
  prompt: string;
  /**
   * К какой игре относится вопрос (см. каталог игр в lib/quizGames.ts).
   */
  game: 'sabantuy' | 'kartinki';
  theme?: ('sabantuy' | 'history' | 'geography' | 'people' | 'language' | 'other') | null;
  /**
   * Влияет только на оформление/подпись; механика у всех — выбор варианта.
   */
  format?: ('choice' | 'trueMyth' | 'translate') | null;
  difficulty?: ('easy' | 'medium' | 'hard') | null;
  /**
   * От 2 до 4 вариантов. Ровно один отметьте как правильный.
   */
  options: {
    text: string;
    correct?: boolean | null;
    id?: string | null;
  }[];
  /**
   * Показывается после ответа — ради этого факта игра и затевается.
   */
  explanation?: string | null;
  /**
   * Проверяемый источник (ссылка или издание). Обязателен для образовательной игры — общий для всех языков.
   */
  source?: string | null;
  /**
   * Для игры «Угадай по картинке»: имя файла в /public/quiz без расширения (напр. koresh).
   */
  image?: string | null;
  /**
   * Ссылка на страницу-источник изображения (атрибуция, напр. Викисклад). Показывается под фото.
   */
  imageSource?: string | null;
  /**
   * Необязательно — короткая подсказка по желанию.
   */
  hint?: string | null;
  /**
   * Меньше — раньше. Пусто — в конце, по дате.
   */
  order?: number | null;
  /**
   * Служебный — для идемпотентного сида. Вручную не заполнять.
   */
  key?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Обезличенные результаты игры-угадайки. На сайте — агрегат (счётчик игроков, средний балл, распределение).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-results".
 */
export interface QuizResult {
  id: number;
  score: number;
  total: number;
  /**
   * Slug игры. Пусто — ранние результаты (Знаток Сабантуя).
   */
  game?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Подписчики на анонс праздника. Содержат email (152-ФЗ) — доступ только у персонала. Рассылку-напоминание орги делают вручную ближе к дате.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  name?: string | null;
  /**
   * Обязательно. Посетитель подтверждает согласие при подписке.
   */
  consent: boolean;
  source?: ('website' | 'other') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Розыгрыш призов. Заявки участников — в коллекции «Заявки на розыгрыш» (ПДн, доступ у персонала).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "raffle".
 */
export interface Raffle {
  id: number;
  title: string;
  description?: string | null;
  prize?: string | null;
  /**
   * Если включено — на сайте показывается форма участия.
   */
  isOpen?: boolean | null;
  /**
   * Поставьте галку и сохраните — система выберет случайного победителя из заявок, закроет приём и снимет эту галку.
   */
  drawNow?: boolean | null;
  /**
   * Заполняется автоматически при розыгрыше.
   */
  winner?: (number | null) | RaffleEntry;
  drawnAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Заявки на участие в розыгрыше. Содержат персональные данные (152-ФЗ) — доступ только у персонала.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "raffle-entries".
 */
export interface RaffleEntry {
  id: number;
  fullName: string;
  phone: string;
  raffle: number | Raffle;
  /**
   * Обязательно. Участник подтверждает согласие при подаче заявки.
   */
  consent: boolean;
  source?: ('website' | 'other') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Фото/видео от посетителей. Постмодерация: видно сразу, скрывайте/удаляйте здесь при жалобах. Медиа хранится в Object Storage (objectKey), не на боксе.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  kind: 'photo' | 'video';
  /**
   * media/<phase>/<yyyymm>/<uuid>.<ext> — путь файла в бакете.
   */
  objectKey: string;
  /**
   * Опц. кадр-обложка для видео.
   */
  posterKey?: string | null;
  mime: string;
  bytes?: number | null;
  width?: number | null;
  height?: number | null;
  durationSec?: number | null;
  /**
   * Файлы №2…№20 поста (обложка — поля выше). Лента показывает их мозаикой, клик открывает галерею.
   */
  media?:
    | {
        kind: 'photo' | 'video';
        objectKey: string;
        posterKey?: string | null;
        mime: string;
        bytes?: number | null;
        width?: number | null;
        height?: number | null;
        durationSec?: number | null;
        id?: string | null;
      }[]
    | null;
  authorName?: string | null;
  caption?: string | null;
  phase: 'preparation' | 'festival';
  /**
   * Обязательно. Посетитель подтверждает при загрузке.
   */
  consent: boolean;
  status?: ('visible' | 'hidden' | 'removed') | null;
  hiddenReason?: string | null;
  likeCount?: number | null;
  commentCount?: number | null;
  viewCount?: number | null;
  battleWins?: number | null;
  battleShows?: number | null;
  reportCount?: number | null;
  ipHash?: string | null;
  ownerHash?: string | null;
  ownerVisitor?: number | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Лайки публикаций ленты. Агрегат likeCount — на самой публикации.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submission-reactions".
 */
export interface SubmissionReaction {
  id: number;
  submission: number | Submission;
  ipHash?: string | null;
  ownerHash?: string | null;
  ownerVisitor?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Просмотры публикаций ленты. Агрегат viewCount — на самой публикации.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submission-views".
 */
export interface SubmissionView {
  id: number;
  submission: number | Submission;
  ipHash?: string | null;
  ownerHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Комментарии к публикациям ленты. Постмодерация: видно сразу, скрывайте при жалобах.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submission-comments".
 */
export interface SubmissionComment {
  id: number;
  submission: number | Submission;
  authorName?: string | null;
  body: string;
  status?: ('visible' | 'hidden' | 'removed') | null;
  hiddenReason?: string | null;
  reportCount?: number | null;
  ipHash?: string | null;
  ownerHash?: string | null;
  ownerVisitor?: number | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Жалобы посетителей на публикации/комментарии. На пороге цель скрывается авто.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-reports".
 */
export interface ContentReport {
  id: number;
  targetType: 'submission' | 'comment';
  targetId: number;
  reason?: string | null;
  ipHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Раунды игры «Фотобитва». Счёт побед/показов — на самих публикациях (battleWins/battleShows), отдельно от лайков ленты.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photo-battles".
 */
export interface PhotoBattle {
  id: number;
  winner: number | Submission;
  loser: number | Submission;
  ipHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Посетители, вошедшие через ВКонтакте. Содержат vkId/имя/аватар (152-ФЗ) — доступ только у персонала. Закрепляют «своё» в «Народной ленте».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visitors".
 */
export interface Visitor {
  id: number;
  /**
   * Идентификатор пользователя ВКонтакте (стабильный ключ аккаунта).
   */
  vkId: string;
  name?: string | null;
  avatarUrl?: string | null;
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles: ('admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'registrations';
        value: number | Registration;
      } | null)
    | ({
        relationTo: 'poll-votes';
        value: number | PollVote;
      } | null)
    | ({
        relationTo: 'quiz-questions';
        value: number | QuizQuestion;
      } | null)
    | ({
        relationTo: 'quiz-results';
        value: number | QuizResult;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'raffle';
        value: number | Raffle;
      } | null)
    | ({
        relationTo: 'raffle-entries';
        value: number | RaffleEntry;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'submission-reactions';
        value: number | SubmissionReaction;
      } | null)
    | ({
        relationTo: 'submission-views';
        value: number | SubmissionView;
      } | null)
    | ({
        relationTo: 'submission-comments';
        value: number | SubmissionComment;
      } | null)
    | ({
        relationTo: 'content-reports';
        value: number | ContentReport;
      } | null)
    | ({
        relationTo: 'photo-battles';
        value: number | PhotoBattle;
      } | null)
    | ({
        relationTo: 'visitors';
        value: number | Visitor;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  heroImage?: T;
  publishedAt?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  startDate?: T;
  endDate?: T;
  location?: T;
  venue?: T;
  category?: T;
  heroImage?: T;
  content?: T;
  capacity?: T;
  registrationEnabled?: T;
  publishedAt?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  description?: T;
  date?: T;
  event?: T;
  coverImage?: T;
  photos?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  videos?:
    | T
    | {
        url?: T;
        title?: T;
        id?: T;
      };
  publishedAt?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations_select".
 */
export interface RegistrationsSelect<T extends boolean = true> {
  fullName?: T;
  phone?: T;
  email?: T;
  event?: T;
  competitionType?: T;
  participants?: T;
  comment?: T;
  consent?: T;
  status?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "poll-votes_select".
 */
export interface PollVotesSelect<T extends boolean = true> {
  option?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-questions_select".
 */
export interface QuizQuestionsSelect<T extends boolean = true> {
  prompt?: T;
  game?: T;
  theme?: T;
  format?: T;
  difficulty?: T;
  options?:
    | T
    | {
        text?: T;
        correct?: T;
        id?: T;
      };
  explanation?: T;
  source?: T;
  image?: T;
  imageSource?: T;
  hint?: T;
  order?: T;
  key?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-results_select".
 */
export interface QuizResultsSelect<T extends boolean = true> {
  score?: T;
  total?: T;
  game?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  consent?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "raffle_select".
 */
export interface RaffleSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  prize?: T;
  isOpen?: T;
  drawNow?: T;
  winner?: T;
  drawnAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "raffle-entries_select".
 */
export interface RaffleEntriesSelect<T extends boolean = true> {
  fullName?: T;
  phone?: T;
  raffle?: T;
  consent?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  kind?: T;
  objectKey?: T;
  posterKey?: T;
  mime?: T;
  bytes?: T;
  width?: T;
  height?: T;
  durationSec?: T;
  media?:
    | T
    | {
        kind?: T;
        objectKey?: T;
        posterKey?: T;
        mime?: T;
        bytes?: T;
        width?: T;
        height?: T;
        durationSec?: T;
        id?: T;
      };
  authorName?: T;
  caption?: T;
  phase?: T;
  consent?: T;
  status?: T;
  hiddenReason?: T;
  likeCount?: T;
  commentCount?: T;
  viewCount?: T;
  battleWins?: T;
  battleShows?: T;
  reportCount?: T;
  ipHash?: T;
  ownerHash?: T;
  ownerVisitor?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submission-reactions_select".
 */
export interface SubmissionReactionsSelect<T extends boolean = true> {
  submission?: T;
  ipHash?: T;
  ownerHash?: T;
  ownerVisitor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submission-views_select".
 */
export interface SubmissionViewsSelect<T extends boolean = true> {
  submission?: T;
  ipHash?: T;
  ownerHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submission-comments_select".
 */
export interface SubmissionCommentsSelect<T extends boolean = true> {
  submission?: T;
  authorName?: T;
  body?: T;
  status?: T;
  hiddenReason?: T;
  reportCount?: T;
  ipHash?: T;
  ownerHash?: T;
  ownerVisitor?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-reports_select".
 */
export interface ContentReportsSelect<T extends boolean = true> {
  targetType?: T;
  targetId?: T;
  reason?: T;
  ipHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photo-battles_select".
 */
export interface PhotoBattlesSelect<T extends boolean = true> {
  winner?: T;
  loser?: T;
  ipHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visitors_select".
 */
export interface VisitorsSelect<T extends boolean = true> {
  vkId?: T;
  name?: T;
  avatarUrl?: T;
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * План территории + объекты (еда, парковка, туалеты, сцены). Объекты удобно подписать прямо на картинке плана.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "festival-map".
 */
export interface FestivalMap {
  id: number;
  /**
   * Схема территории. Подпишите объекты прямо на изображении — список ниже дублирует их для удобства.
   */
  planImage?: (number | null) | Media;
  intro?: string | null;
  points?:
    | {
        label: string;
        type?: ('stage' | 'food' | 'entrance' | 'parking' | 'wc' | 'medical' | 'other') | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Тексты главной страницы: герой, заголовки секций, карточки. Картинки/иконки — в коде.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  heroEyebrow?: string | null;
  heroTitleAccent?: string | null;
  heroTagline?: string | null;
  featuresEyebrow?: string | null;
  featuresTitle?: string | null;
  /**
   * Текст карточек. Иконка/обложка — в коде; строки сопоставляются по «Ключу».
   */
  features?:
    | {
        key: string;
        title?: string | null;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  cultureEyebrow?: string | null;
  cultureTitle?: string | null;
  cultureLead?: string | null;
  /**
   * Текст карточек-разделов. Иконка/ссылка — в коде; строки по «Ключу».
   */
  cultureCards?:
    | {
        key: string;
        title?: string | null;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Прямой эфир через VK. Включите трансляцию в приложении ВКонтакте, вставьте ссылку на видео/эфир и поставьте «Эфир идёт». На /efir появится плеер.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-stream".
 */
export interface LiveStream {
  id: number;
  isLive?: boolean | null;
  /**
   * Ссылка вида https://vk.com/video-123456_789012 (или код «video_ext»). Поддерживается только VK.
   */
  vkUrl?: string | null;
  /**
   * Напр.: «Прямой эфир открытия с майдана».
   */
  note?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Название сайта и подписи пунктов меню. Порядок и адреса ссылок — в коде.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  brand?: string | null;
  /**
   * Подписи пунктов меню. Адрес — в коде; строки по «Ключу».
   */
  nav?:
    | {
        key: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Строка копирайта в подвале.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "festival-map_select".
 */
export interface FestivalMapSelect<T extends boolean = true> {
  planImage?: T;
  intro?: T;
  points?:
    | T
    | {
        label?: T;
        type?: T;
        note?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroTitleAccent?: T;
  heroTagline?: T;
  featuresEyebrow?: T;
  featuresTitle?: T;
  features?:
    | T
    | {
        key?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  cultureEyebrow?: T;
  cultureTitle?: T;
  cultureLead?: T;
  cultureCards?:
    | T
    | {
        key?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-stream_select".
 */
export interface LiveStreamSelect<T extends boolean = true> {
  isLive?: T;
  vkUrl?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  brand?: T;
  nav?:
    | T
    | {
        key?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}